CREATE TABLE atlas_driver_offer_bpp.cancellation_and_now_show_charge_configs ();

ALTER TABLE atlas_driver_offer_bpp.cancellation_and_now_show_charge_configs ADD COLUMN currency character varying(255) NOT NULL;
ALTER TABLE atlas_driver_offer_bpp.cancellation_and_now_show_charge_configs ADD COLUMN free_cancellation_time_seconds integer NOT NULL;
ALTER TABLE atlas_driver_offer_bpp.cancellation_and_now_show_charge_configs ADD COLUMN id character varying(36) NOT NULL;
ALTER TABLE atlas_driver_offer_bpp.cancellation_and_now_show_charge_configs ADD COLUMN max_cancellation_charge double precision NOT NULL;
ALTER TABLE atlas_driver_offer_bpp.cancellation_and_now_show_charge_configs ADD COLUMN max_waiting_time_at_pickup_seconds integer NOT NULL;
ALTER TABLE atlas_driver_offer_bpp.cancellation_and_now_show_charge_configs ADD COLUMN merchant_id character varying(36) NOT NULL;
ALTER TABLE atlas_driver_offer_bpp.cancellation_and_now_show_charge_configs ADD COLUMN merchant_operating_city_id character varying(36) NOT NULL;
ALTER TABLE atlas_driver_offer_bpp.cancellation_and_now_show_charge_configs ADD COLUMN min_cancellation_charge double precision NOT NULL;
ALTER TABLE atlas_driver_offer_bpp.cancellation_and_now_show_charge_configs ADD COLUMN per_metre_cancellation_charge double precision NOT NULL;
ALTER TABLE atlas_driver_offer_bpp.cancellation_and_now_show_charge_configs ADD COLUMN per_minute_cancellation_charge double precision NOT NULL;
ALTER TABLE atlas_driver_offer_bpp.cancellation_and_now_show_charge_configs ADD COLUMN percentage_of_ride_fare_to_be_charged double precision NOT NULL;
ALTER TABLE atlas_driver_offer_bpp.cancellation_and_now_show_charge_configs ADD COLUMN vehicle_service_tier_type text NOT NULL;
ALTER TABLE atlas_driver_offer_bpp.cancellation_and_now_show_charge_configs ADD COLUMN created_at timestamp with time zone NOT NULL default CURRENT_TIMESTAMP;
ALTER TABLE atlas_driver_offer_bpp.cancellation_and_now_show_charge_configs ADD COLUMN updated_at timestamp with time zone NOT NULL default CURRENT_TIMESTAMP;
ALTER TABLE atlas_driver_offer_bpp.cancellation_and_now_show_charge_configs ADD PRIMARY KEY ( id);