imports:
  Merchant: Domain.Types.Merchant
  MerchantOperatingCity: Domain.Types.MerchantOperatingCity
  EmailOTPConfig: Email.Types
  KaptureConfig: IssueManagement.Common
  ExotelMapping: Domain.Types.Extra.RiderConfig
  Value: Data.Aeson
  NominalDiffTime: Kernel.Prelude
  Seconds: Kernel.Types.Common

RiderConfig:
  tableName: rider_config

  derives: "Show, Generic, ToJSON, FromJSON"

  fields:
    merchantOperatingCityId: Id MerchantOperatingCity
    enableLocalPoliceSupport: Bool
    localPoliceNumber: Maybe Text
    enableSupportForSafety: Bool
    videoFileSizeUpperLimit: Int
    timeDiffFromUtc: Seconds
    enableEmergencyContactAddedMessage: Bool
    safetyCheckStartTime: Seconds
    safetyCheckEndTime: Seconds
    trackingShortUrlPattern: Text
    specialZoneRadius: Int
    appUrl: Text
    collectAutoCompleteData: Maybe Bool
    distanceWeightage: Int
    collectMMIRouteData: Maybe Bool
    isAvoidToll: Bool
    autoUnblockSafetyCenterAfterDays: Int
    placeNameCacheExpiryDays: Maybe Int
    bookingSyncStatusCallSecondsDiffThreshold: Maybe Int
    kaptureQueue: Text # deprecated
    kaptureConfig: IssueManagement.Common.KaptureConfig
    emailOtpConfig: Maybe Email.Types.EmailOTPConfig
    ivrTriggerDelay: NominalDiffTime
    policeTriggerDelay: NominalDiffTime
    exotelAppIdMapping: Maybe ExotelMapping
    hardLimitForSafetyJobs: Int
    exotelStatusCheckScheduler : Int
    incidentReportSupport: Bool

  beamType:
    ivrTriggerDelay: Maybe Seconds
    policeTriggerDelay: Maybe Seconds
    hardLimitForSafetyJobs: Maybe Seconds
    exotelStatusCheckScheduler : Maybe Seconds
    incidentReportSupport: Maybe Bool

  constraints:
    merchantOperatingCityId: PrimaryKey

  fromTType:
    ivrTriggerDelay: fromMaybe 3000 (Kernel.Utils.Common.secondsToNominalDiffTime <$> ivrTriggerDelay)|E
    policeTriggerDelay: fromMaybe 60 (Kernel.Utils.Common.secondsToNominalDiffTime <$> policeTriggerDelay)|E
    hardLimitForSafetyJobs: fromMaybe 21600 ((.getSeconds) <$> hardLimitForSafetyJobs)|E
    exotelStatusCheckScheduler: fromMaybe 120 ((.getSeconds) <$> exotelStatusCheckScheduler)|E
    incidentReportSupport: fromMaybe False incidentReportSupport|E

  toTType:
    ivrTriggerDelay: (Just . Kernel.Utils.Common.nominalDiffTimeToSeconds)|I
    policeTriggerDelay: (Just . Kernel.Utils.Common.nominalDiffTimeToSeconds)|I
    hardLimitForSafetyJobs: Just $ Kernel.Types.Common.Seconds hardLimitForSafetyJobs|E
    exotelStatusCheckScheduler: Just $ Kernel.Types.Common.Seconds exotelStatusCheckScheduler|E
    incidentReportSupport: Just incidentReportSupport|E

  default:
    enableLocalPoliceSupport: "false"
    enableSupportForSafety: "false"
    videoFileSizeUpperLimit: "15000000"
    enableEmergencyContactAddedMessage: "true"
    appUrl: "'nammayatri.in/link/rider/rmxw'"
    timeDiffFromUtc: "19800"
    safetyCheckStartTime: "75600"
    safetyCheckEndTime: "21600"
    trackingShortUrlPattern: "'nammayatri.in/t/'"
    specialZoneRadius: "150"
    distanceWeightage: "70"
    isAvoidToll: "true"
    autoUnblockSafetyCenterAfterDays: "14"
    kaptureQueue: "''"
    kaptureConfig: "'{\"kaptureQueue\":\"\", \"disposition\":\"\"}'"

  queries:
    findByMerchantOperatingCityId:
      kvFunction: findOneWithKV
      where: merchantOperatingCityId

    findExotelAppletMappingByMOCID:
      kvFunction: findOneWithKV
      where: merchantOperatingCityId

  sqlType:
    emailOtpConfig: "json"
    kaptureConfig: "json"
    exotelAppIdMapping: "json"

  extraOperations:
    - EXTRA_DOMAIN_TYPE_FILE