imports:
  Merchant: Domain.Types.Merchant
  MerchantOperatingCity: Domain.Types.MerchantOperatingCity
  EmailOTPConfig: Email.Types
  KaptureConfig: IssueManagement.Common

RiderConfig:
  tableName: rider_config

  fields:
    merchantOperatingCityId: Id MerchantOperatingCity
    enableLocalPoliceSupport: Bool
    localPoliceNumber: Maybe Text
    enableSupportForSafety: Bool
    videoFileSizeUpperLimit: Int
    timeDiffFromUtc: Seconds
    enableEmergencyContactAddedMessage: Bool
    safetyCheckStartTime: Seconds
    safetyCheckEndTime: Seconds
    trackingShortUrlPattern: Text
    specialZoneRadius: Int
    appUrl: Text
    collectAutoCompleteData: Maybe Bool
    distanceWeightage: Int
    collectMMIRouteData: Maybe Bool
    isAvoidToll: Bool
    autoUnblockSafetyCenterAfterDays: Int
    placeNameCacheExpiryDays: Maybe Int
    bookingSyncStatusCallSecondsDiffThreshold: Maybe Int
    kaptureQueue: Text # deprecated
    kaptureConfig: IssueManagement.Common.KaptureConfig
    emailOtpConfig: Maybe Email.Types.EmailOTPConfig
    settleCancellationFeeBeforeNextRide: Maybe Bool

  constraints:
    merchantOperatingCityId: PrimaryKey

  default:
    enableLocalPoliceSupport: "false"
    enableSupportForSafety: "false"
    videoFileSizeUpperLimit: "15000000"
    enableEmergencyContactAddedMessage: "true"
    appUrl: "'nammayatri.in/link/rider/rmxw'"
    timeDiffFromUtc: "19800"
    safetyCheckStartTime: "75600"
    safetyCheckEndTime: "21600"
    trackingShortUrlPattern: "'nammayatri.in/t/'"
    specialZoneRadius: "150"
    distanceWeightage: "70"
    isAvoidToll: "true"
    autoUnblockSafetyCenterAfterDays: "14"
    kaptureQueue: "''"
    kaptureConfig: "'{\"kaptureQueue\":\"\", \"disposition\":\"\"}'"

  queries:
    findByMerchantOperatingCityId:
      kvFunction: findOneWithKV
      where: merchantOperatingCityId
  sqlType:
    emailOtpConfig: "json"
    kaptureConfig: "json"