imports:
  Merchant: Domain.Types.Merchant
  MerchantOperatingCity: Domain.Types.MerchantOperatingCity
  BatchSplitByPickupDistance: SharedLogic.Allocator.Jobs.SendSearchRequestToDrivers.Handle.Internal.DriverPool.Config
  BatchSplitByPickupDistanceOnRide: SharedLogic.Allocator.Jobs.SendSearchRequestToDrivers.Handle.Internal.DriverPool.Config
  OnRideRadiusConfig: SharedLogic.Allocator.Jobs.SendSearchRequestToDrivers.Handle.Internal.DriverPool.Config
  PoolSortingType: SharedLogic.Allocator.Jobs.SendSearchRequestToDrivers.Handle.Internal.DriverPool.Config
  Seconds: Kernel.Types.Common
  IndianState: Kernel.Types.Beckn.Context
  ServiceTierType: Domain.Types.ServiceTierType
  Area: Lib.Types.SpecialLocation
  Common: Domain.Types.Common
  TimeBound : Domain.Types.TimeBound
  Currency: Kernel.Utils.Common
  DayOfWeek: Data.Time
  Centesimal: Kernel.Types.Common

DriverPoolConfig:
  tableName: driver_pool_config

  fields:
    id: Id DriverPoolConfig
    merchantId: Id Merchant
    merchantOperatingCityId: Id MerchantOperatingCity
    minRadiusOfSearch: Meters
    maxRadiusOfSearch: Meters
    radiusStepSize: Meters
    driverPositionInfoExpiry: Maybe Seconds
    actualDistanceThreshold: Maybe Meters
    maxDriverQuotesRequired: Int
    driverQuoteLimit: Int
    driverRequestCountLimit: Int
    driverBatchSize: Int
    distanceBasedBatchSplit: "[BatchSplitByPickupDistance]"
    maxNumberOfBatches: Int
    maxParallelSearchRequests: Int
    poolSortingType: PoolSortingType
    singleBatchProcessTime: Seconds
    tripDistance: Meters
    radiusShrinkValueForDriversOnRide: Meters
    driverToDestinationDistanceThreshold: Meters
    driverToDestinationDuration: Seconds
    scheduleTryTimes: "[Int]"
    area: Area
    timeBounds: TimeBound|NoRelation
    batchSizeOnRide: Int
    onRideRadiusConfig: "[OnRideRadiusConfig]"
    onRideBatchSplitConfig: "[BatchSplitByPickupDistanceOnRide]"
    enableForwardBatching: Bool
    createdAt: UTCTime
    updatedAt: UTCTime
    vehicleVariant: Maybe ServiceTierType|NoRelation
    tripCategory: Text
    maxParallelSearchRequestsOnRide: Int
    thresholdToIgnoreActualDistanceThreshold: Maybe Meters
    actualDistanceThresholdOnRide: Maybe Meters
    currentRideTripCategoryValidForForwardBatching : "[Text]"
    distanceUnit: DistanceUnit

  beamFields:
    distanceUnit:
      distanceUnit: Maybe DistanceUnit

  fromTType:
    distanceUnit: Kernel.Prelude.fromMaybe Kernel.Types.Common.Meter|I

  toTType:
    distanceUnit: Kernel.Prelude.Just|I


  beamInstance:
    - MakeTableInstances
    - Custom Domain.Types.UtilsTH.mkCacParseInstance
  constraints:
    id: PrimaryKey

  sqlType:
    distanceBasedBatchSplit: text[]
    onRideRadiusConfig: text[]
    scheduleTryTimes: integer[]
    timeBounds: Text
    onRideBatchSplitConfig: text[]

  default:
    tripCategory: "'All'"
    area: "'Default'"
    distanceBasedBatchSplit: "Array ['BatchSplitByPickupDistance { batchSplitSize = 1, batchSplitDelay = 0 }', 'BatchSplitByPickupDistance { batchSplitSize = 1, batchSplitDelay = 4 }']"
    scheduleTryTimes: "'{1800, 900, 300}'"
    timeBounds: "'Unbounded'"
    batchSizeOnRide: "10"
    onRideRadiusConfig: "ARRAY[]::TEXT[]"
    currentRideTripCategoryValidForForwardBatching: "Array ['OneWay_OneWayOnDemandDynamicOffer']"
    onRideBatchSplitConfig: "Array ['BatchSplitByPickupDistanceOnRide { batchSplitSize = 1, batchSplitDelay = 0 }', 'BatchSplitByPickupDistanceOnRide { batchSplitSize = 1, batchSplitDelay = 4 }']"
    enableForwardBatching: "false"
    maxParallelSearchRequestsOnRide: "1"

  queries:
    findAllByMerchantOpCityId:
      kvFunction: findAllWithOptionsKV
      where: merchantOperatingCityId
      orderBy: tripDistance

MerchantState:
  tableName: merchant_state

  fields:
    merchantId: Id Merchant
    state: IndianState
    allowedDestinationStates: "[IndianState]"

  excludedFields: [merchantOperatingCityId]

  constraints:
    merchantId: PrimaryKey
    state: PrimaryKey

  sqlType:
    allowedDestinationStates: text[]

  queries:
    findByMerchantIdAndState:
      kvFunction: findOneWithKV
      where:
        and: [merchantId, state]

ValueAddNP:
  tableName: value_add_np

  fields:
    subscriberId: Text
    enabled: Bool

  constraints:
    subscriberId: PrimaryKey

  excludedFields: [merchantId, merchantOperatingCityId]

  queries:
    findAll:
      kvFunction: findAllWithKV
      where: enabled

CancellationAndNoShowChargeConfigs:
  tableName: cancellation_and_now_show_charge_configs

  fields:
    id : Id CancellationAndNoShowChargeConfigs
    merchantId: Id Merchant
    merchantOperatingCityId: Id MerchantOperatingCity
    vehicleServiceTierType: ServiceTierType|NoRelation
    currency: Currency
    minCancellationCharge: HighPrecMoney
    maxCancellationCharge: HighPrecMoney
    perMetreCancellationCharge: HighPrecMoney
    perMinuteCancellationCharge: HighPrecMoney
    maxWaitingTimeAtPickupSeconds:  Seconds
    freeCancellationTimeSeconds: Seconds
    percentageOfRideFareToBeCharged: HighPrecMoney

  queries:
    findByMerchantOpCityIdAndServiceTierType:
      kvFunction: findOneWithKV
      where:
        and: [merchantOperatingCityId, vehicleServiceTierType]

  cachedQueries:
    findByMerchantOpCityIdAndServiceTierType:
      keyParams: [merchantOperatingCityId, vehicleServiceTierType]
      dbQuery: findByMerchantOpCityIdAndServiceTierType
      dbQueryParams: [merchantOperatingCityId, vehicleServiceTierType]
      queryType: FindAndCache

SurgePricing:
  tableName: surge_pricing

  fields:
    id: Id SurgePricing
    sourceHex: Text
    dayOfWeek: Text
    hourOfDay: Int
    surgeMultiplier: Centesimal

  queries:
    findByHexDayAndHour:
      kvFunction: findOneWithKV
      where:
        and: [sourceHex, dayOfWeek, hourOfDay]

  constraints:
    id: PrimaryKey

  sqlType:
    surgeMultiplier: double precision

  excludedFields: [merchantId, merchantOperatingCityId]

  cachedQueries:
    findByHexDayAndHour:
      returnType: One
      withCrossAppRedis: true
      queryType: FindAndCache
      dbQuery: findByHexDayAndHour
      dbQueryParams: [sourceHex, dayOfWeek, hourOfDay]
      keyParams: [sourceHex, dayOfWeek, hourOfDay]
